name: Build Desktop App

on:
  release:
    types: [created, edited]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter build windows --dart-define=COMMIT_SHA=${{ github.sha }}
      - uses: denoland/setup-deno@v1
      - run: >
          deno run -A ./script/upload.ts
          --releaseId ${{ github.event.release.id }}
          --name windows
          --path ./build/windows/x64/runner/Release
          --githubToken ${{ secrets.GITHUB_TOKEN }}
          --githubRepositoryOwner ${{ github.repository_owner }}
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter build macos --dart-define=COMMIT_SHA=${{ github.sha }}
      - uses: denoland/setup-deno@v1
      - run: >
          deno run -A ./script/upload.ts
          --releaseId ${{ github.event.release.id }}
          --name macos
          --path ./build
          --githubToken ${{ secrets.GITHUB_TOKEN }}
          --githubRepositoryOwner ${{ github.repository_owner }}
