name: Build Desktop App

on:
  release:
    types: [created, edited]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter build windows --dart-define=COMMIT_SHA=${{ github.sha }}
      - run: Compress-Archive -Path . -DestinationPath ../../../../../windows-nonogram.zip
        working-directory: ./build/windows/x64/runner/Release
      - uses: denoland/setup-deno@v1
      - run: >
          deno run -A ./script/upload.ts
          --releaseId ${{ github.event.release.id }}
          --name windows-nonogram.zip
          --path ./windows-nonogram.zip
          --githubToken ${{ secrets.GITHUB_TOKEN }}
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter build macos --dart-define=COMMIT_SHA=${{ github.sha }}
      - run: zip -ry ../../../../../macos-nonogram.zip ./nonogram.app
        working-directory: ./build/macos/Build/Products/Release
      - uses: denoland/setup-deno@v1
      - run: >
          deno run -A ./script/upload.ts
          --releaseId ${{ github.event.release.id }}
          --name macos-nonogram.zip
          --path ./macos-nonogram.zip
          --githubToken ${{ secrets.GITHUB_TOKEN }}
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      # https://qiita.com/fia/items/435b72b9ef6ca9e0410c
      - run: sudo apt install clang curl pkg-config ninja-build cmake libgtk-3-dev libblkid-dev liblzma-dev unzip
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter build linux --dart-define=COMMIT_SHA=${{ github.sha }}
      # https://qiita.com/yone098@github/items/bba8a42de6b06e40983b
      - run: pwd;find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'
      - run: zip -ry ../../../../../linux-nonogram.zip ./nonogram
        working-directory: ./build/linux/x64/release/bundle
      - run: pwd;find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'
      - uses: denoland/setup-deno@v1
      - run: >
          deno run -A ./script/upload.ts
          --releaseId ${{ github.event.release.id }}
          --name linux-nonogram.zip
          --path ./linux-nonogram.zip
          --githubToken ${{ secrets.GITHUB_TOKEN }}
  build-linux-arm64:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - uses: actions/checkout@v4
      - run: sudo apt install clang curl pkg-config ninja-build cmake libgtk-3-dev libblkid-dev liblzma-dev unzip
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter build linux --dart-define=COMMIT_SHA=${{ github.sha }}
      - run: pwd;find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'
      - run: zip -ry ../../../../../linux-arm64-nonogram.zip ./nonogram
        working-directory: ./build/linux/x64/release/bundle
      - run: pwd;find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'
      - uses: denoland/setup-deno@v1
      - run: >
          deno run -A ./script/upload.ts
          --releaseId ${{ github.event.release.id }}
          --name linux-arm64-nonogram.zip
          --path ./linux-arm64-nonogram.zip
          --githubToken ${{ secrets.GITHUB_TOKEN }}
